### PR TITLE
bump to crystal 1.0.0

### PR DESCRIPTION
**Pull request by mearsten**
Details: https://github.com/crystal-lang/shards/releases/tag/v0.11.0

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Thanks. You can relax the minitest constraint to just `~> 1.0`.

Isn't `crystal: ">= 1.0"` also needed?

**Comment by kostya** [comment]
yes, need such line: `crystal: ">= 1.0.0, < 2.0"` or `crystal: ">= 0.35.1, < 2.0"`, and btw is not shard.lock not used, and not needed here, just to be in gitignore.

**Comment by mearsten** [comment]
> Thanks. You can relax the minitest constraint to just `~> 1.0`.

Fixed.

> Isn't `crystal: ">= 1.0"` also needed?

Thank you Julien, I added that too.

**Comment by mearsten** [comment]
> and btw is not shard.lock not used, and not needed here, just to be in gitignore.

Do you mean that `shard.lock` should not be kept in git?

**Comment by kostya** [comment]
I think this can be merged, many projects related on pool repo. Shard.lock can be removed later

**Comment by mearsten** [comment]
> many projects related on pool repo

Yes. At least [crystal-redis](https://github.com/stefanwille/crystal-redis) depends.

**Comment by ysbaddaden** [comment]
Thanks for bump. I used `crystal: *`, which should have been the actual default, and the library didn't any fix since 2016 (aka forever). I released v0.2.4 which is identical the v0.2.3, except shards now considers it (sigh).

**Pull request closed without merging**
